DROP TABLE USER IF EXISTS;
CREATE TABLE USER (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO USER VALUES (1001, 'User1', 'password1');
INSERT INTO USER VALUES (1002, 'User2', 'password2');
INSERT INTO USER VALUES (1003, 'User3', 'password3');